"""2_added_reset_password_table

Revision ID: 5057e9ac6bec
Revises: 1050f3afcca4
Create Date: 2024-01-13 01:21:53.947165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "5057e9ac6bec"
down_revision: Union[str, None] = "1050f3afcca4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reset_password_codes",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires", sa.types.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("hashed_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reset_password_codes")
    # ### end Alembic commands ###
